title: My Static Website
email: CoryWBoris@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my site, and I'm Cory Boris. Hope you find something interesting here!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.CoryWBoris.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: CoryWBoris

# Build settings
theme: minima  # or any other theme you are using
sass:
  style: compressed
  implementation: sass-embedded
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# include pages
include:
  - _pages
# make the image a background image, including the image name for reference
# image:
#   background: CoryPortrait.JPG
#   background_size: cover
#   background_position: center
#   background_darken: 0.6

#   background_position: center

#   background_size: cover
#   background_position: center
#   background_darken: 0.6